[theme]
primaryColor = "#7c6af7"
backgroundColor = "#00072D"
secondaryBackgroundColor = "#1e1e2e"
textColor = "#e0e0e0"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false
